application:
  id: close-auth

server:
  port: 8085
  shutdown: graceful
  servlet:
    context-path: /cauth

logging:
  level:
    root: info

spring:
  application:
    name: ${application.id}
  security:
    user:
      name: admin
      password: admin
---

jwt:
  security:
    secret-key: Y/Eag7nA6m8hOeBHpZxZWXwLmdDezzcx+x76Gc6RvFQ=
    expiration:
      time:
        in-hours: 2

spring:
  profiles:
    active: dev
    group:
      dev: dev
      prod: prod

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/close_auth
    username: bhaskar
    password: bhaskar
    driver-class-name: org.postgresql.Driver
  flyway:
    locations: classpath:db/migration
    repair-on-migrate: true
  jpa:
    hibernate:
    show-sql: true
    properties:
      hibernate:
        format-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  mail:
    host: sandbox.smtp.mailtrap.io
    port: 587
    username: 4d11686ea71354
    password: 4905e9e6facfa3
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000

redis:
  host: localhost
  port: 6379
  password: redis_password
  timeout: 1000
  max-active: 8
  max-idle: 8
  min-idle: 0
  use-ssl: false

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:postgresql://prod-host:5432/close_auth
    username: ${PROD_DB_USER}
    password: ${PROD_DB_PASS}
  flyway:
    locations: classpath:db/migration

redis:
  host: ${PROD_REDIS_HOST}
  port: ${PROD_REDIS_PORT}
  password: ${PROD_REDIS_PASS}
  timeout: 1000
  max-active: 8
  max-idle: 8
  min-idle: 0
  use-ssl: false