application:
  id: close-auth

server:
  port: 8085
  shutdown: graceful
  servlet:
    context-path: /cauth

logging:
  level:
    root: info

spring:
  application:
    name: ${application.id}
  security:
    user:
      name: admin
      password: admin
---

jwt:
  security:
    secret-key: Y/Eag7nA6m8hOeBHpZxZWXwLmdDezzcx+x76Gc6RvFQ=
    expiration:
      time:
        in-hours: 2

spring:
  profiles:
    active: dev
    group:
      dev: dev
      prod: prod

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/close_auth
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  flyway:
    locations: classpath:db/migration
    repair-on-migrate: true
  jpa:
    hibernate:
    show-sql: true
    properties:
      hibernate:
        format-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect


---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:postgresql://prod-host:5432/close_auth
    username: ${PROD_DB_USER}
    password: ${PROD_DB_PASS}
  flyway:
    locations: classpath:db/migration