application:
  id: close-auth

server:
  port: 8085
  shutdown: graceful
  servlet:
    context-path: /cauth

logging:
  level:
    root: trace

spring:
  profiles:
    active: dev
    group:
      dev: dev
      prod: prod
  application:
    name: ${application.id}
  security:
    user:
      name: admin
      password: admin

jwt:
  security:
    secret-key: Y/Eag7nA6m8hOeBHpZxZWXwLmdDezzcx+x76Gc6RvFQ=
    expiration:
      time:
        in-hours: 2

# app configuration w.r.t password
app:
  password-reset:
    token:
      expiry: 10 # in minutes
  frontend:
    reset-password:
      url: http://localhost:5173/close-auth/forgot-passsword


---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/close_auth
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  flyway:
    locations: classpath:db/migration
    repair-on-migrate: true
  jpa:
    hibernate:
    show-sql: true
    properties:
      hibernate:
        format-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  mail:
    host: sandbox.smtp.mailtrap.io
    port: 587
    username: closeauth@gmail.com
    password: czsilpodziornmpl
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000

redis:
  host: localhost
  port: 6379
  username: default
  password: redis_password
  timeout: 1000
  max-active: 8
  max-idle: 8
  min-idle: 0
  use-ssl: false
  app:
    rate-limit:
      forgot-password: 5
      validate-token : 10
      reset-password : 5
      window-minutes : 15


---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:postgresql://prod-host:5432/close_auth
    username: ${PROD_DB_USER}
    password: ${PROD_DB_PASS}
  flyway:
    locations: classpath:db/migration

redis:
  host: ${PROD_REDIS_HOST}
  port: ${PROD_REDIS_PORT}
  password: ${PROD_REDIS_PASS}
  timeout: 1000
  max-active: 8
  max-idle: 8
  min-idle: 0
  use-ssl: false

  # Rate limiting configuration w.r.t password operations
  app:
  rate-limit:
    forgot-password: 5
    validate-token: 10
    reset-password: 5
    window-minutes: 15